mongo_server:
  image: mongo
  container_name: wzdt_mongo
  volumes:
    - ./db:/data/db
  expose:
    - "27017"
  ports:
    - "27017:27017"
redis_server:
  image: redis
  container_name: wzdt_redis
  volumes:
    - ./docker:/kerwin
  expose:
   - "6379"
  ports:
   - "6379:6379"
  command: ["redis-server", "/kerwin/config/redis.conf"]
python_server:
  build: ./docker
  #image: wzdt_python
  container_name: wzdt_python
  links:
    - redis_server
    - mongo_server
  volumes:
    - .:/kerwin
    - ./docker/mitmproxy:/root/.mitmproxy
  ports:
   - "8080:8080"
   - "5000:5000"


